apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ginger"
  annotations:
    "humanitec.com/orgId": "htc-demo-04"
    "humanitec.com/appId": "ginger"
  links:
    - url: https://wuckertdaughertyharveystammmacgyver.newapp.io/
      title: Ginger DEV

spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  dependsOn:
    - component:fred
#  consumesApis:
#    - TimeOfDay
